### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DaveAtkinsonXMOS**
Modified README.md to point out that this repo is now obselete.

### CODE REVIEW

**Comment by DaveAtkinsonXMOS** [comment]
Opened in error. I don't want this to be a fork.

**Comment by DaveAtkinsonXMOS** [comment]
Don't have write access, so I've reopened this pull request.

**Comment by DaveAtkinsonXMOS** [comment]
Suggest deleting the script file, too. What say you all?

**Comment by BrennanGit** [comment]
We can probably keep discussion in https://github.com/xmos/vocalfusion_3510_avs_setup/pull/44

**Review by mbanth — APPROVED** [review]
The Raed Me change is fine.  I'm also happy with deleting the script.  I suggest deleting everything except the Read Me, in fact.

**Pull request merged**
